app_web:
    resource: '@AppBundle/Controller/Web'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_api:
    type:     annotation
    resource: "@AppBundle/Controller/Api"

