services:
#    adaptivex_mercadopago.example:
#        class: Adaptivex\MercadopagoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.mercadopago:
            class: MercadoPago